#   Adam Stępień - Informatyka w Biznesie - WSB Toruń - 2021r
#   GUI stworzyłem w programie QtDesigner, a następnie plik .ui przekonwertowałem na plik .py
#       za pomogą biblioteki pyuic5 
#           Plik .ui został dołączony do folderu z programem

# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'pesel_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 99)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.birthDate = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.birthDate.setObjectName("birthDate")
        self.gridLayout.addWidget(self.birthDate, 0, 2, 1, 1)
        self.giveMeDateLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.giveMeDateLbl.setObjectName("giveMeDateLbl")
        self.gridLayout.addWidget(self.giveMeDateLbl, 0, 1, 1, 1)
        self.generateBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.generateBtn.setObjectName("generateBtn")
        self.gridLayout.addWidget(self.generateBtn, 0, 3, 1, 1)
        self.newPeselInfoLbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.newPeselInfoLbl.setObjectName("newPeselInfoLbl")
        self.gridLayout.addWidget(self.newPeselInfoLbl, 1, 1, 1, 1)
        self.newPesel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.newPesel.setAlignment(QtCore.Qt.AlignCenter)
        self.newPesel.setObjectName("newPesel")
        self.gridLayout.addWidget(self.newPesel, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Generator PESEL"))
        self.giveMeDateLbl.setText(_translate("Dialog", "Podaj swoją datę urodzenia: "))
        self.generateBtn.setText(_translate("Dialog", "&Generuj PESEL"))
        self.newPeselInfoLbl.setText(_translate("Dialog", "Twój nowy numer PESEL: "))
        self.newPesel.setText(_translate("Dialog", "Nowy Pesel"))
